service: lunchero-serverless

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  app_name: Lunchero
  dynamo_name: ${self:custom.app_name}-dynamo
  sqs_name: ${self:custom.app_name}-sqs
 
provider:
  name: aws
  runtime: python3.6 # or python3.7, supported as of November 2018
  memorySize: 128
  environment:
    DYNAMODB_TABLE: ${self:custom.dynamo_name} 
  iamRoleStatements:
    - Effect: Allow
      Action:
      - sqs:DeleteMessage
      - sqs:ReceiveMessage
      - sqs:SendMessage
      - sqs:SendMessageBatch
      Resource: "arn:aws:sqs:*:*:${self:custom.sqs_name}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

package:
  exclude:
    - ./** 
  include:
    - ./chatless/**

resources:
  Resources:
    BufferQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sqs_name}
        MessageRetentionPeriod: 12000
        VisibilityTimeout: 60
    LuncherbotDynamoDbTable: 
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sortkey
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sortkey
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

functions:
  chatbot:
    handler: chatless.chatbot_example_dynamodb.handle
    environment:
      SLACKBOT_OAUTH: 'xoxb-3360794059-669882893493-7MejyIqpXvJLCgGna42MRmAj'
      PROVIDER_REGION: "${self:provider.region}"
      DYNAMODB_TABLE: "${self:provider.environment.DYNAMODB_TABLE}"
      SQS_QUEUE:
        Ref: BufferQueue
    events:
      - http:
          path: chat
          method: post
      - sqs:
          arn:
            Fn::GetAtt:
              - BufferQueue
              - Arn

